### ISSUE TITLE
IE 11 error "Unspecified Error" from jspanel.js on line 1295/7

### ISSUE THREAD

**Issue by geoffblandrbs** [Flyer53/jsPanel4#103] opened 2019-11-07 09:24 UTC
Only occurs on IE11 and not on Chrome, prevents panel being shown.

Line 1295:
`panel.style.left = "calc(".concat(panel.style.left, " + ").concat(position.offsetX, ")"); // offsetX`

Fails when `panel.style.left` is empty with an "Unspecified Error".

Fix replace lines 1295..1297 with the following:

```
if (panel.style.left == "") {
  panel.style.left = "calc(0px + ".concat(position.offsetX, ")"); // offsetX
}
else {
  panel.style.left = "calc(".concat(panel.style.left, " + ").concat(position.offsetX, ")"); // offsetX
}
		
if (panel.style.top == "") {
  panel.style.top = "calc(0px + ".concat(position.offsetY, ")"); // offsetY
}
else {
  panel.style.top = "calc(".concat(panel.style.top, " + ").concat(position.offsetY, ")"); // offsetY
}

```

This is probably not the best fix - it may be better to ensure that 'applyPositionOffset()' is not called with empty left and top positions.

**Comment by Flyer53** [comment] 2019-11-07 10:17
@geoffblandrbs 
What OS, IE, jsPanel versions do you use?
And can you please show the panel code producing this error.
I can't reproduce the error. At least not with all the option position examples on the docs pages using IE11 version 11.418.18362.0 on a Windows 10 machine.

Note:
At the time the function applying the offsets is called within the positioning function css left and top values are already applied to the panel (even if they are "0px" values). So as far as I can say it can never happen that `if (panel.style.left == "")` is evaluated to `true`. I have no idea why your code seems to fix it in your case.

**Comment by geoffblandrbs** [comment] 2019-11-07 11:25
Thanks for the prompt reply.

Windows 7, IE Version 11.0.9600.19507. Document mode is "Edge (Default)".

I can't think of an easier way to show you the error occurring than a screen shot:

![jspanel](https://user-images.githubusercontent.com/6451079/68381344-6c556e80-0149-11ea-9f8c-282e065d9544.JPG)

Will send on the panel code as soon as I get an OK to do so.

**Comment by Flyer53** [comment] 2019-11-07 11:31
Ok, thanks
I'll see whether I can reproduce it on a Windows 7 machine ...

**Comment by Flyer53** [comment] 2019-11-07 16:07
Well ... my oldest machine runs Windows 8.1. There IE11 (same version as you use) doesn't show any problems. Without being  able to reproduce the error I don't have an idea what to do about it. "Unspecified Error" isn't very helpful either.

IE11 is known to have issues with css `calc()` - https://caniuse.com/#search=calc.
Did you try some other offset settings?

**Comment by Flyer53** [comment] 2019-11-07 19:43
Meanwhile I installed a Windows 7 in a virtual machine incl. IE11
Still can't reproduce your issue ...

Question:
Microsoft ends support for Windows 7 in January 2020. This in mind it doesn't seem a good thing to me to stick with a Win7/IE combination. Wouldn't it be a lot better to upgrade both OS and browser.
And btw ... MS EDGE Beta is available for Windows 7 as well with the final release planned for January as far as I know.

**Comment by geoffblandrbs** [comment] 2019-11-08 08:40
Thanks for the help.

Here is the code I use to create the panel, maybe something here?

```
/**
* Create a pop-up
* @param aTitle the title of the pop-up
* @param aContent the content of the pop-up
* @returns a pop-up
*/
function createPopup(aTitle, aContent) {
  
  // Build the pop-up
  var popup_panel = jsPanel.create({
    
    // Set the title 
    headerTitle : aTitle,
    
    // Set the content
    content : aContent,
    
    // Only show the close button
    headerControls : {
      maximize : "remove",
      minimize  : "remove",
      smallify  : "remove"
    },
    
    // Position cascading from top-left to bottom-right 
    position: {
      my: 'left-top',
      at: 'left-top',
      minTop: HEADER_SIZE, 
      of: function () {
        return jsPanel.getPanels().length > 1 ? jsPanel.getPanels()[1] : 'window';
      },
      offsetX: function () {
        return jsPanel.getPanels().length > 1 ? 50 : 0;
      },
      offsetY: function () {
        return jsPanel.getPanels().length > 1 ? 50 : 0;
      }
    },
    
    // Auto-size the panel
    panelSize : {
      width : "auto",
      height : "auto"
    },
    
    // Keep the panel on the screen when dragged
    dragit : {
      // Use the drag stop event as containment option does not seem to work
      stop : function(panel, position, event) {
        
        // Don't allow panel to slide under menu bar
        if (position.top < HEADER_SIZE) {
          panel.reposition({
            my: 'left-top',
            at: 'left-top',
            offsetX: position.left,
            offsetY: 32
         });
        }
        
        // Don't allow panel to slide under footer bar
        if (position.top > (window.innerHeight - (FOOTER_SIZE + POPUP_HEADER_SIZE) ) ) {
          panel.reposition({
            my: 'left-top',
            at: 'left-top',
            offsetX: position.left,
            offsetY: (window.innerHeight - (FOOTER_SIZE + POPUP_HEADER_SIZE) )
          });         
        }
      }
    },
    
    // Use bootstrap look and feel
    theme : "bootstrap-info"
  });
  
  // Re-attach the clipboard to clipable elements on this pop-up as well
  var clipable_elements = document.getElementsByClassName('clipable');
  var clipboard = new Clipboard(clipable_elements);
  
  // Set colours to match
  popup_panel.header.style.backgroundColor = HEADER_BACKGROUND_COLOUR;
  popup_panel.headertitle.style.color = HEADER_TEXT_COLOUR;

  // Return the newly created popup
  return popup_panel;
}

```

I did try with other issues so calc() doesn't seem to be the problem, I would expect it to fail with a string of " + 0px" which is what happens when panel.style.left is null. I think as you previously mentioned the real issue is why panel.style.left is null when this is called.

Windows 7 and IE 11 are the standards for the company I support the web site for, they have plans to upgrade but this won't be done for several years yet.

**Comment by Flyer53** [comment] 2019-11-08 13:59
Sorry that I can't help more. But without being able to reproduce your issue ...
However, there's one idea that might help. Although it would require some recoding on your side:

`applyPositionOffset()` is not called when neither `offsetX` nor `offsetY` parameters are used.
So instead use parameter [modify](https://jspanel.de/api.html#options/position/modify) to calculate the new position.
Basically it would work like:
```javascript
jsPanel.create({
  position: {
    my: "left-top",
    at: "left-top",
    modify: function(position) {
      this.left = 'calc(' + position.left + ' + 20px)';
      this.top = 'calc(' + position.top + ' + 20px)';
      return this;
    }
  }
});
```
Since you use a dragit.stop callback repositioning the panel it would be needed there as well.
Btw: the note in your code sample says dragit.containment is not working?

**Comment by geoffblandrbs** [comment] 2019-11-12 14:52
Sorry it took some time to get back an test this. 

But I now also noticed that our version of IE is throwing "Object doesn't support property or method 'match'" in IE, on line 1286.

`if (Number.isInteger(position[offset]) || position[offset].match(/^\d+$/)) {`

position[offset] = 833.84

I have also fixed this by changing the above line 1286 to:

`if (isNaN(position[offset]) == false) {`

**Comment by Flyer53** [comment] 2019-11-12 17:14
@geoffblandrbs 
No problem at all ...
Well, offsets were not meant to have floating point numbers. But it can happen of course and your fix will be in the next release. So thanks for providing it 👍

Anything about using modify instead of offsets?

**Comment by geoffblandrbs** [comment] 2019-11-13 08:22
Sorry it took a while to find the time to test this, but adding the modify function does not fix the issue at least for the first panel creation.

First time I create a panel we hit the error as panel.style.left = "". Next time I create a panel panel.style.left = "0px" and so it works.

The modify function only gets called after the applyPositionOffset() method and so this does not fix the issue - if the error occurs then IE fails and the modify function is never called.

Stack trace on initial error:

applyPositionOffset [Line: 1298, Col: 5], jspanel.js
position [Line: 1208, Col: 7], jspanel.js
create [Line: 5035, Col: 7], jspanel.js

**Comment by Flyer53** [comment] 2019-11-13 09:05
I don't understand. The code is ...
```javascript
if (position.offsetX || position.offsetY) {
    pos = this.applyPositionOffset(panel, pos, position);
}
```
The only other occurance of `applyPositionOffset()` is the function definition itself. So how can the function be called when neither `offsetX` nor `offsetY` are set?

In all tests I made `applyPositionOffset()` is never called when both `offsetX` and `offsetY` are not set.

**Comment by geoffblandrbs** [comment] 2019-11-13 09:23
I think your code should be 

```
    if (_position.offsetX() || _position.offsetY()) {
      pos = this.applyPositionOffset(panel, pos, _position); //console.log('pos after applying offsets:', pos);
    }

```
and not 

```
    if (_position.offsetX || _position.offsetY) {
      pos = this.applyPositionOffset(panel, pos, _position); //console.log('pos after applying offsets:', pos);
    }

```

**Comment by Flyer53** [comment] 2019-11-13 14:11
My idea behind using `modify` was to avoid `offsetX` and `offsetY` completely in order to avoid the error. Calculate the offsets within `modify`. So your code sample could look like:
```javascript
jsPanel.create({
    position: {
        my: 'left-top',
        at: 'left-top',
        of: function () {
            return jsPanel.getPanels().length > 1 ? jsPanel.getPanels()[1] : 'window';
        },
        modify: function(position) {
            var left = `calc(${position.left} + 50px)`;
            var top = `calc(${position.top} + 50px)`;
            return {left: left, top: top};
        }
    }
});
```

**Comment by geoffblandrbs** [comment] 2019-11-13 15:03
Using the code you have above, the first panel opened can no longer be dragged left and right and is stuck with the left side side at 0. It can be dragged up and down the page however.
Subsequent panels open directly on top of the original panel rather than offset to the right and down. 

Also, regardless, I still think your code `if (position.offsetX || position.offsetY)` needs to cope with offsetX/Y being functions that return empty strings or 0 and if so don't call applyPositionOffset().

**Comment by geoffblandrbs** [comment] 2019-11-13 15:04
FWIW I do have it all working - just with the changes I listed in my first post here.

**Comment by Flyer53** [comment] 2019-11-13 16:10
Ok, for some reason the first panel in IE ends up having no value for style left (the drag function relies on the panel having style values for left and top) and IE can't handle template literals. My example updated:
```javascript
jsPanel.create({
    position: {
        my: 'left-top',
        at: 'left-top',
        of: function () {
            return jsPanel.getPanels()[1] || 'window';
        },
        modify: function(position) {
            // do without template literals
	    var left = 'calc(' + position.left + ' + 50px)';
            var top = 'calc(' + position.top + ' + 50px)';
            return {left: left, top: top};
        }
    },
    callback: function(){
        // ensure panel has a style left value which must not be 'auto'
	var left = getComputedStyle(this).left;
	this.style.left = left === 'auto' ? '0px' : left;
    }
});
```
Checked this only with IE11 on Windows 10 though.

>Also, regardless, I still think your code `if (position.offsetX || position.offsetY)` needs to cope with offsetX/Y being functions and call applyPositionOffset() depending on the result of the function.

In a boolean context functions are truthy, whatever they return. So if either one of offsetX/offsetY is a function `if (position.offsetX || position.offsetY)` will execute `applyPositionOffset()`. And the function itself is executed within `applyPositionOffset()`. So I don't think that's the problem, unless I get something completely wrong. Remember ... I'm not a professional programmer.

However, if you have a solution that works for you ... use it. I don't know how to help further without being able to reproduce the error.

I hope it's not too disappointing for you.

**Comment by Flyer53** [comment] 2019-12-10 10:40
@geoffblandrbs 
Just released v4.9.0.
Would you be willing to check whether it makes any difference?
Regards,
Stefan

**Comment by geoffblandrbs** [comment] 2019-12-10 10:49
Will do - but I will have to do test this in the New Year as I'm just about to leave on holiday. 
Thanks & Happy Xmas.

**Comment by Flyer53** [comment] 2019-12-10 10:56
Sounds good to me.
Enjoy your holidays. I'll be away in a few days as well.
Merry Christmas and a Happy New Year

**Comment by geoffblandrbs** [comment] 2020-01-10 11:35
I have now tested this issue with v4.9.1 and unfortunately the issue still exists on IE.

Unspecified error. File: jspanel.js, Line: 1354, Column: 5

`panel.style.left = "calc(".concat(panel.style.left, " + ").concat(position.offsetX, ")");`

panel.style.left = "" -- Empty string
position.offsetX = "0px"

This only happens as before on first call - subsequent calls have panel.style.left = "0px"

**Comment by geoffblandrbs** [comment] 2020-01-10 12:00
Fix up is as before with these lines replacing lines 1354-1356:

`    if (panel.style.left == "") {
    	panel.style.left = "calc(0px + ".concat(position.offsetX, ")"); // offsetX
		}
		else {
    	panel.style.left = "calc(".concat(panel.style.left, " + ").concat(position.offsetX, ")"); // offsetX
		}
		
		if (panel.style.top == "") {
    	panel.style.top = "calc(0px + ".concat(position.offsetY, ")"); // offsetY
		}
		else {
    	panel.style.top = "calc(".concat(panel.style.top, " + ").concat(position.offsetY, ")"); // offsetY
		}    
`

**Comment by Flyer53** [comment] 2020-01-11 07:28
Thanks for the update.
I'll look at it again and keep you informed.

**Comment by Flyer53** [comment] 2020-01-11 08:26
@geoffblandrbs 
Ok ... as far as I understand the basic problem is that the panel does not have a css `style.left` value on first call. So instead of adding some extra js I added a style attribute to the panel template assigning left/top values of `"0"` ensuring that `style.left` and `style.top` do not return empty strings on first call.

I prepared a [preliminary v4.9.2 to download](https://alpha.jspanel.de/downloads/jspanel-4.9.1.zip) including this change. I'm confident to have it fixed this way ... let me know how it works out please.

**Comment by geoffblandrbs** [comment] 2020-01-14 13:21
Hi, the link above is wrong and points at a v4.9.1 release - but I found your 4.9.2 release at https://alpha.jspanel.de/downloads/jspanel-4.9.2.zip.

I can confirm that this version 4.9.2 fixes the issue on IE. 

Thanks.

**Comment by Flyer53** [comment] 2020-01-15 08:40
@geoffblandrbs 
👍 Just updated repo to v4.9.2 fixing the issue

**Closed by Flyer53** 2020-01-15 08:40 UTC
