### ISSUE TITLE
jspanel status are not sync and correct.

### ISSUE THREAD

**Issue by smkrn110** [Flyer53/jsPanel4#94] opened 2019-07-16 10:25 UTC
I subscribed to event onstatuschange(panel, status), and not getting correct status. 

for example, 

when I clicked minimized (-) it gives status = normalized
also get normalized when click on smallify button.

when I clicked maximized (squarebox) it gives status = minimized
and when I clicked to back from smallify it gives status = smallify

**Comment by Flyer53** [comment] 2019-07-16 13:42
I think there is just a misunderstanding: Look at the example code from the docs and note the comments.
```javascript
jsPanel.create({
  onstatuschange: function(panel, status){
    console.log(status); // logs panel status before it changed
    this.setHeaderTitle(this.status); // ("this" refers to the panel) current status
  }
});
```
+ the value of the `status` argument passed to the handler is the status of the panel before it changed
+ the value of the panel property `status` is the current status

So if you minimize a normalized panel the **argument** `status` of the event handler has the value `'normalized'` and the **property** `status` of the panel has the value `'minimized'`.

As far as I see it you describe exactly the intended behaviour. You just have to distinguish between the event handler argument `status` and the panel property `status`.
+ if you need the current status of the panel use the **panel property** `status`
+ if you for some reason need to know the panel status before it was minimized, maximized and so on use the **argument** `status` from the event handler

**Comment by Flyer53** [comment] 2019-08-06 07:11
@smkrn110 
You did not respond to this topic for 3 weeks now. I would appriciate if you could give some feedback.

**Comment by Flyer53** [comment] 2019-08-28 06:48
@smkrn110 
You did not respond to this issue for another 3 weeks now. So I assume it's irrelevant by now and close the issue.

**Closed by Flyer53** 2019-08-28 06:48 UTC
