### ISSUE TITLE
Autoclose won't perform when use nesteed JSPanel

### ISSUE THREAD

**Issue by theGilles** [Flyer53/jsPanel4#193] opened 2022-08-14 16:05 UTC
Create a JSPanel
```javascript
 mypanel1 = jsPanel.create ({
              id              : 'PanelMapId',
              container       :  el,
              resizeit        : { disable: true },
              borderRadius    : '.5rem',
              contentSize     : '760 550',
              headerTitle     : 'La Cartographie',
              position        : 'center 0 0',
              content         : '<div id="theContainer"></div>',
              headerControls  : { 
                                  close     : 'remove', 
                                  maximize  : 'remove'
                                },
              footerToolbar: [
                  '<span class="flex-auto">Cliquez ici pour valider votre recherche &nbsp&nbsp</span>',
                  '<span class="jsPanel-ftr-btn"><i class="bi bi-search"></i></span>',
              ],
              callback: (panel) => {
                      // handler for the icons
                      for (const btn of panel.footer.querySelectorAll('span')) 
                      {
                          btn.addEventListener('click', (e) => {
                              let cl = e.target.closest('span').classList;
                              alert('on cache la fenêtre et on lance la rechercher');
                          });
                      }
              }
          }
    );
```
create a nesteed JSPanel
```javascript
jsPanel.create({
            headerTitle     : 'aRea - Information',
            content         : '<div style="text-align: center;display: flex;align-items: center;justify-content: center">'+pmsg+'</div>',
            contentSize     : '200 50',
            container       :  el,
            theme           : 'dimgray filledlight',
            borderRadius    : '.5rem',
            headerControls  : 
            { 
              maximize  : 'remove',
              minimize  : 'remove',
              normalize : 'remove',
              smallify  : 'remove'
            },
            animateIn   : 'animate__animated animate__bounceInDown',
            animateOut  : 'animate__animated animate__bounceOutUp',
            autoclose   : {
                            time: '5s',
            },
          });
```
After 5s (here defined time) nothing happens.
Thanks

**Comment by Flyer53** [comment] 2022-08-15 19:00
@theGilles 
Since I can't reproduce the issue my first question is: Does your page load the required css library for the animations you use with options `animateIn` and `animateOut` on the second panel? As mentioned in the description of option [animateOut](https://alpha.jspanel.de/api.html#options/animateOut) for example those animations are not included in the jsPanel css file.

For a quick test replace
```javascript
animateIn   : 'animate__animated animate__bounceInDown',
animateOut  : 'animate__animated animate__bounceOutUp',
```
with
```javascript
animateIn   : 'jsPanelFadeIn',
animateOut  : 'jsPanelFadeOut',
```
These 2 animations are included in the jsPanel css file.

Please let me know whether this is the problem.

**Comment by theGilles** [comment] 2022-08-16 08:28
@theFlyer53
you were right, I used an indefinite animation.
Another point how to center vert/horz a text inside jspanel ?
Thanks

**Comment by Flyer53** [comment] 2022-08-16 19:36
@theGilles 
I would do the centering with a flexbox like:
```javascript
jsPanel.create({
  content: '<div style="display:flex;height:100%"><span style="margin:auto;">some text ...</span></div>'
});
```

**Comment by Flyer53** [comment] 2022-08-20 13:48
@theGilles 
If there are no more questions on this issue please close it.

**Comment by theGilles** [comment] 2022-08-22 08:59
Thanks for all.

**Closed** 2022-08-22 08:59 UTC
